### ISSUE TITLE
Failure in trying to setup a build step

### ISSUE THREAD

**Issue by avinashkolluru** [melezhik/chef-plugin#7]
When i click on 'Run chef client on remote host' nothing happens.
I'm trying this from a Mac and when i observed the network I see the following request failure
```
Request URL: 	http://localhost:9090/$stapler/bound/483943d3-9f58-4999-ad2b-1b3587b527fb/render
Request Method: 	POST
Status Code: 	HTTP/1.1 500 Server Error
Request Headers 22:25:49.000
X-Requested-With:	XMLHttpRequest
X-Prototype-Version:	1.7
User-Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Referer:	http://localhost:9090/job/Items1/configure
Pragma:	no-cache
Host:	localhost:9090
Crumb:	654c68bf-da54-4df8-b9ed-6407361872d9
Content-Type:	application/x-stapler-method-invocation;charset=UTF-8
Content-Length:	2
Connection:	keep-alive
Cache-Control:	no-cache
Accept-Language:	en-US,en;q=0.5
Accept-Encoding:	gzip, deflate
Accept:	text/javascript, text/html, application/xml, text/xml, */*
Sent Cookie
JSESSIONID.f33706b0:	3w9nbg8tzieltqwvcg02vg5l
Response Headers Δ19ms
X-SSH-Endpoint:	localhost:56919
X-Jenkins-Session:	72e5cf87
X-Jenkins-CLI2-Port:	56920
X-Jenkins-CLI-Port:	56920
X-Jenkins:	1.626
X-Instance-Identity:	MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj9yZ8jC7qetQKeAkLlyFlUIITf23yMZ5QyHoeJclb6jNefGOmydEkHik3piyJWmaw/gABnphsu+EDAxSuODT1+7pCQGpYJyQFbEfjMSP0xVNmbY+qbueJD9FAOSmAXZRxICkRDMIS7jVecc9L6lxzU6sdZyMcrhcA4OUKTH0wp9zfcMyQcGXFIL/sRliuof6Bg1BjtJTXLavGhBYQ7sl+m5S2vfI/2t+jJvazm2Wp5NaUSmIxCJ9uLAPg2K+bjUGHIwlVRnsSceblIRnVjBFHwtp+Tk9wAByNhBoG0K9ULrGAmcoSQ3+xm3Gy+WwsIaMwx31ei4Al5XSXX4uUnNczwIDAQAB
X-Hudson-Theme:	default
X-Hudson-CLI-Port:	56920
X-Hudson:	1.395
x-frame-options:	sameorigin
X-Content-Type-Options:	nosniff
Server:	Jetty(winstone-2.8)
Expires:	0
Content-Type:	text/html;charset=UTF-8
Content-Length:	4958
Content-Encoding:	gzip
Cache-Control:	no-cache,no-store,must-revalidate

```

**Comment by melezhik** [comment]
Hi @avinashkolluru ! Thanks for your request ...

> observed the network I see the following request failure ...

The information you provide seemed is not sufficient for me. Could you please also add jenkins log?
Right now all that I see that "500 Server Error" returned , ( from Jenkins? )

**Comment by avinashkolluru** [comment]
@melezhik 
```
getConfigPage -> /chef_builder/config
Aug 30, 2015 12:11:08 AM hudson.widgets.RenderOnDemandClosure$1 generateResponse
WARNING: Failed to evaluate the template closure
org.apache.commons.jelly.JellyTagException: jar:file:/Users/Shared/Jenkins/Home/war/WEB-INF/lib/jenkins-core-1.626.jar!/lib/form/hetero-list.jelly:131:100: <st:include> jar:file:/Users/Shared/Jenkins/Home/war/WEB-INF/lib/jenkins-core-1.626.jar!/lib/form/entry.jelly:73:23: <d:invokeBody> (NoMethodError) undefined method `get' for nil:NilClass
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:275)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:91)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:178)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
	at org.jruby.java.proxies.ConcreteJavaProxy$2.call(ConcreteJavaProxy.java:52)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
	at org.jruby.RubyClass.newInstance(RubyClass.java:855)
	at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrNBlock.call(JavaMethod.java:278)
	at org.jruby.java.proxies.ConcreteJavaProxy$3.call(ConcreteJavaProxy.java:148)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueBodyNode.interpret(RescueBodyNode.java:108)
	at org.jruby.ast.RescueNode.handleJavaException(RescueNode.java:207)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:140)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:75)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:126)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:163)
	at org.jruby.javasupport.proxy.JavaProxyConstructor$2.invoke(JavaProxyConstructor.java:224)
	at org.jruby.proxy.org.kohsuke.stapler.jelly.jruby.JRubyJellyScript$Proxy1.run(Unknown Source)
	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:147)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.OtherwiseTag.doTag(OtherwiseTag.java:41)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.ChooseTag.doTag(ChooseTag.java:38)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:63)
	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:53)
	at hudson.widgets.RenderOnDemandClosure$1.generateResponse(RenderOnDemandClosure.java:99)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.handleHttpResponse(HttpResponseRenderer.java:124)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.generateResponse(HttpResponseRenderer.java:69)
	at org.kohsuke.stapler.Function.renderResponse(Function.java:113)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:98)
	at org.kohsuke.stapler.MetaClass$JavaScriptProxyMethodDispatcher.doDispatch(MetaClass.java:490)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:813)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:199)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by melezhik** [comment]
OK, I was able to reproduce this issue for myself. It seem chef-plugin , latest version 0.1.6 is not compatible with jenkins 1.626. Right now you may downgrade chef plugin  to 0.1.5 using this link - http://repo.jenkins-ci.org/releases/org/jenkins-ci/ruby-plugins/chef/0.1.5/ , at least I have tested it against jenkins version 1.626 and it works fine.

**Comment by melezhik** [comment]
Version 0.1.5 has some drawbacks thought, I am working on version 0.1.7 to fix this issue and still have all changes shipped for 0.1.6. I will let you know soon.

**Comment by melezhik** [comment]
I have tested RC - http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/ruby-plugins/chef/0.1.7-SNAPSHOT/ and this issue is fixed for me . Try this version for awhile till I release new version to official repository

**Comment by melezhik** [comment]
0.1.7 release is here - http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/ruby-plugins/chef/0.1.7

**Comment by melezhik** [comment]
0.1.7. should be at official jenkins index soon, not sure how much time it requires though. Close this issue, please reopen it if the issue  appear again. Thanks.

**Comment by ghost** [comment]
@melezhik Awesome.
Thanks for the super fast fix. Tested and works fine now.
